# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dba9e1c58bbf273ac46ef11662c9f282fdbafc6c317e9ea7236bffab76f0886b5af5b321bd9354c0cf45f75c22f312afb0fbd06795013bd2bf4b259dfb6ddbf

test:
  secret_key_base: dcc6c4306063507498cfe61544c1530b5ddabf6944c551e210fef6a6a45cbb3e368c25f0ec82d007942e833e5e86a04eab172b2f0762bfc5815f2b261c8887a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
